//go:build browser

package remote_test

// Shoots the phone-remote screenshots used in the README. Everything it
// shows is invented for the shoot: fictional stations, songs, lyrics and
// example.com listeners, generated by a fake engine into a sandboxed
// data directory, so the pictures never carry anyone's real library.
//
// Run with: make screenshots

import (
	"context"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"iar/internal/audio"
	"iar/internal/export"
	"iar/internal/session"
	"iar/internal/snippets"
)

// shotScale is the device pixel ratio the shoot renders at, so the
// pictures stay sharp on a high-density display.
const shotScale = 3

// demoPrompt seeds the playing station. Its first comma segment becomes
// the track title on the page, so it reads like a song name.
const demoPrompt = "Harbour Lights, neon synthwave, warm analog pads, driving bassline"

// demoLyrics are the words the fake engine reports for every track.
const demoLyrics = `[Verse]
Headlights comb the harbour wall
Radio static, half a song
Counting bridges as they fall
Behind me all night long

[Chorus]
Harbour lights, keep burning
Harbour lights, I'm turning home`

// demoSong is one invented saved song.
type demoSong struct {
	tag, title, genre, lang string
	lyrics                  string
	seconds                 int
	when                    time.Time
}

// demoLibrary is the saved-songs shelf the Saved screenshot shows.
var demoLibrary = []demoSong{
	{
		tag: "night drive", title: "Harbour Lights", genre: "neon synthwave, warm analog pads",
		lang: "en", seconds: 154, when: time.Date(2026, 3, 14, 22, 41, 0, 0, time.UTC),
		lyrics: demoLyrics,
	},
	{
		tag: "night drive", title: "Static On The Overpass", genre: "synthwave, driving bassline",
		lang: "en", seconds: 168, when: time.Date(2026, 3, 14, 23, 12, 0, 0, time.UTC),
		lyrics: "[Verse]\nSix lanes wide and nobody home\n\n[Chorus]\nStatic on the overpass",
	},
	{
		tag: "night drive", title: "Faros de Medianoche", genre: "synthwave, warm pads",
		lang: "es", seconds: 149, when: time.Date(2026, 3, 15, 0, 3, 0, 0, time.UTC),
		lyrics: "[Verso]\nLos faros de medianoche\n\n[Coro]\nY la carretera sigue",
	},
	{
		tag: "gym", title: "Iron Weather", genre: "energetic electronic rock, motivational",
		lang: "en", seconds: 141, when: time.Date(2026, 3, 12, 7, 25, 0, 0, time.UTC),
		lyrics: "[Verse]\nOne more set and the storm breaks\n\n[Chorus]\nIron weather, hold the line",
	},
	{
		tag: "focus", title: "Long Division", genre: "beatless ambient pads",
		seconds: 212, when: time.Date(2026, 3, 10, 9, 2, 0, 0, time.UTC),
		lyrics: "",
	},
}

// demoSessions are the named stations listed above the presets.
var demoSessions = []struct{ name, prompt string }{
	{"harbour-lights", demoPrompt},
	{"morning-focus", "Morning Focus, beatless ambient pads, no drums"},
}

// TestScreenshots drives the remote through the pages the README shows
// and writes a PNG for each into $IAR_SHOTS.
func TestScreenshots(t *testing.T) {
	shots := os.Getenv("IAR_SHOTS")
	if shots == "" {
		t.Skip("set IAR_SHOTS=<dir> to shoot the README screenshots")
	}
	need(t, "geckodriver", "firefox", "pactl", "ffmpeg", "go")
	if err := os.MkdirAll(shots, 0o755); err != nil {
		t.Fatal(err)
	}
	shot := func(name string) string { return filepath.Join(shots, name) }

	sinkName, _ := nullSink(t)

	// A music-mode sandbox with a fake engine: real queue, prefetch and
	// steering behaviour, no GPU, and no helper model, so the shoot
	// produces the same pictures on any machine.
	// The fake engine renders instantly, so the buffer's real 120-minute
	// render-ahead would spawn dozens of encodes at once. Floor every
	// depth (the config clamps below 10/10/5) so the shoot renders the
	// handful of songs the pages actually show.
	sb := prepareSandbox(t, "acestep", `"vocal_languages":["English","Spanish","Japanese"],`+
		`"buffer":{"phased":true,"render_low_minutes":5}`)
	// Resume the seeded station rather than starting from the prompt, so
	// the now-playing line names a station instead of a generated
	// session id. --no-llm keeps the shoot reproducible: with a helper
	// model reachable the titles would differ from machine to machine.
	sb.args = []string{"--no-llm", "--session", demoSessions[0].name}
	seedEngineLayout(t, sb)
	fe := startFakeEngine(t, filepath.Join(sb.dir, "data", "state"))
	fe.setTrackSeconds(150)
	fe.setLyrics(demoLyrics)
	seedLibrary(t, sb)
	seedSessions(t, sb)
	// A shoot that fails should say why: the structured log carries the
	// generation errors the interface only summarises.
	t.Cleanup(func() {
		if !t.Failed() {
			return
		}
		data, err := os.ReadFile(filepath.Join(sb.dir, "data", "logs", "iar.log"))
		if err != nil {
			return
		}
		lines := strings.Split(strings.TrimSpace(string(data)), "\n")
		if len(lines) > 40 {
			lines = lines[len(lines)-40:]
		}
		t.Logf("last log lines:\n%s", strings.Join(lines, "\n"))
	})
	finishSandbox(t, sb)

	driver := startGeckodriver(t, sinkName)
	w := newWebDriverScaled(t, driver, shotScale)

	// --- the login page ---
	w.navigate(sb.base + "/")
	waitFor(t, 10*time.Second, "login redirect", func() bool { return strings.HasSuffix(w.url(), "/login") })
	w.screenshot(shot("remote-login.png"))

	loginAdmin(t, w, sb.base)

	// --- the live screen, playing ---
	waitFor(t, 20*time.Second, "a track to be playing", func() bool {
		var now string
		w.exec(`var e=document.getElementById('now'); return e ? e.textContent : '';`, &now)
		return now != "" && !strings.Contains(now, "…")
	})
	// Let the machine finish stocking before the phone starts banking:
	// a device can only download what is offered, and starting while
	// one track is listed is a race the picture loses half the time.
	waitFor(t, 120*time.Second, "the machine to offer a few songs", func() bool {
		var q struct {
			Tracks []struct {
				ID string `json:"id"`
			} `json:"tracks"`
		}
		w.execAsync(`var cb=arguments[arguments.length-1]; fetch('/api/queue').then(function(r){return r.json()}).then(cb);`, &q)
		return len(q.Tracks) >= 3
	})
	// Buffered playback is what a phone actually does, so it is what
	// the picture should show: the device's own bank of songs, the
	// Flush chip that empties it, and a seek bar that works because
	// the song is a whole file sitting on the phone.
	w.exec(`document.getElementById('buffered').click();
		var sel = document.getElementById('buflevel');
		sel.value = 'steady';
		sel.dispatchEvent(new Event('change'));
		return true;`, nil)
	w.click("#play")
	// Wait for a bank worth showing: songs stacked up ahead of the one
	// playing, and no "nothing new yet" note. Caught too early the
	// picture shows the one state a listener never wants to see.
	var lastBank string
	t.Cleanup(func() {
		if t.Failed() {
			t.Logf("device bank at the end: %s", lastBank)
		}
	})
	waitFor(t, 200*time.Second, "a healthy device bank", func() bool {
		var st struct {
			Playing bool   `json:"playing"`
			Count   string `json:"count"`
			Note    string `json:"note"`
			Hidden  bool   `json:"hidden"`
			Ahead   int    `json:"ahead"`
		}
		w.exec(`var a=[document.getElementById('bufaudio0'),document.getElementById('bufaudio1')];
			var el=null; a.forEach(function (x) { if (x && !x.paused && x.currentTime > 0.5) el = x; });
			var pill=(document.getElementById('streamstate')||{}).textContent||"";
			var m=pill.match(/(\d+) ahead/);
			return {
				playing: !!el,
				count: (document.getElementById('devcount')||{}).textContent||"",
				note: (document.getElementById('devnote')||{}).textContent||"",
				hidden: !!document.getElementById('devrow').hidden,
				ahead: m ? parseInt(m[1], 10) : 0
			};`, &st)
		var q struct {
			Tracks []struct {
				Kind string `json:"kind"`
			} `json:"tracks"`
		}
		w.execAsync(`var cb=arguments[arguments.length-1]; fetch('/api/queue').then(function(r){return r.json()}).then(cb);`, &q)
		lastBank = fmt.Sprintf("playing=%v hidden=%v ahead=%d count=%q note=%q serverRows=%d",
			st.Playing, st.Hidden, st.Ahead, st.Count, st.Note, len(q.Tracks))
		return st.Playing && !st.Hidden && st.Note == "" && st.Ahead >= 1 &&
			!strings.HasPrefix(st.Count, "1 song ")
	})
	waitFor(t, 20*time.Second, "lyrics on the page", func() bool {
		var lyr string
		w.exec(`return document.getElementById('lyrics').textContent;`, &lyr)
		return strings.Contains(lyr, "Harbour lights")
	})
	// Give the buffer a moment to bank a song or two, so the page does
	// not advertise an empty one. Not worth failing the shoot over.
	for i := 0; i < 40; i++ {
		var meta string
		w.exec(`return document.getElementById('meta').textContent;`, &meta)
		if !strings.Contains(meta, "0 ready") {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	// Open every station band so the list below the fold looks alive.
	w.exec(`document.querySelectorAll('#sessions details').forEach(function (d) { d.open = true; }); return true;`, nil)
	var nowTitle, nowMeta string
	w.exec(`return document.getElementById('now').textContent;`, &nowTitle)
	w.exec(`return document.getElementById('meta').textContent;`, &nowMeta)
	var devBank string
	w.exec(`var e=document.getElementById('devbank'); return e ? e.textContent : '';`, &devBank)
	t.Logf("live screen: now=%q meta=%q bank=%q", nowTitle, nowMeta, devBank)
	w.screenshot(shot("remote-player.png"))

	// --- the lyrics of the playing track, scrolled into view ---
	w.exec(`document.getElementById('lyricscard').scrollIntoView({block:'start'}); return true;`, nil)
	w.screenshot(shot("remote-lyrics.png"))
	w.exec(`document.getElementById('scroll').scrollTop = 0; return true;`, nil)

	// --- the saved-songs shelf, with one of them playing ---
	w.click("#mode-saved")
	waitFor(t, 10*time.Second, "the saved songs to be listed", func() bool {
		var n int
		w.exec(`return document.querySelectorAll('#chunks .chunk').length;`, &n)
		return n == len(demoLibrary)
	})
	// The shelf is shown doing its job: a song playing, its name and
	// facts at the top of the screen and the position row under them.
	w.click(`#chunks button[aria-label="Play Harbour Lights"]`)
	waitFor(t, 20*time.Second, "the saved position row to follow the song", func() bool {
		var running bool
		w.exec(`var r=document.getElementById('savedseekrow'), a=document.getElementById('savedaudio');
			return !r.className.includes('disabled') && !!a && !a.paused
				&& isFinite(a.duration) && a.duration > 0;`, &running)
		return running
	})
	// A frame of a song a few seconds in reads as playing; one parked at
	// zero reads as broken. The clock is put somewhere deliberate rather
	// than wherever the shoot happened to catch it.
	w.exec(`document.getElementById('savedaudio').currentTime = 41; return true;`, nil)
	waitFor(t, 10*time.Second, "the position row to catch up", func() bool {
		var at string
		w.exec(`return document.getElementById('savedseeknow').textContent;`, &at)
		return at == "0:41"
	})
	w.screenshot(shot("remote-saved.png"))
	w.click("#mode-live")

	// --- the settings sheet ---
	w.click("#more")
	waitFor(t, 10*time.Second, "the settings sheet", func() bool {
		var open bool
		w.exec(`var s=document.getElementById('sheet'); return !!s && s.open;`, &open)
		return open
	})
	w.screenshot(shot("remote-settings.png"))
	w.click("#sheetclose")

	// --- inviting a listener ---
	w.navigate(sb.base + "/users")
	w.typeInto("form[action='/users/create'] input[name=email]", "listener@example.com")
	w.click("form[action='/users/create'] button[type=submit]")
	waitFor(t, 10*time.Second, "the invite link", func() bool {
		var link string
		w.exec(`var l=document.getElementById('link'); return l ? l.value : '';`, &link)
		return link != ""
	})
	w.screenshot(shot("remote-users.png"))
}

// seedEngineLayout lays out just enough of an engine install on disk for
// the app to adopt the fake daemon.
func seedEngineLayout(t *testing.T, sb *sandbox) {
	t.Helper()
	engineDir := filepath.Join(sb.dir, "data", "engine")
	os.MkdirAll(filepath.Join(engineDir, ".venv"), 0o755)
	os.MkdirAll(filepath.Join(engineDir, "checkpoints", "acestep-v15-turbo"), 0o755)
	os.WriteFile(filepath.Join(engineDir, "pyproject.toml"), []byte("[project]\n"), 0o644)
	os.WriteFile(filepath.Join(engineDir, "checkpoints", "acestep-v15-turbo", "weights.bin"), []byte("x"), 0o644)
}

// seedLibrary writes the invented saved songs, each an MP3 with its ID3
// tags and a lyrics file beside it, exactly as a real save leaves them.
func seedLibrary(t *testing.T, sb *sandbox) {
	t.Helper()
	root := filepath.Join(sb.dir, "data", "snippets")
	// The sandbox lays down a placeholder chunk of its own; the shoot
	// shows only the invented shelf.
	if err := os.RemoveAll(root); err != nil {
		t.Fatal(err)
	}
	for _, s := range demoLibrary {
		path := snippets.Path(root, s.tag, s.title, s.lang, s.when)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := export.EncodeMP3(context.Background(), tone(s.seconds, 220+float64(len(s.title)%7)*40), path,
			export.MP3Options{Title: s.title, Subtitle: s.genre, Album: snippets.Slug(s.tag)}); err != nil {
			t.Fatal(err)
		}
		if s.lyrics != "" {
			if err := os.WriteFile(snippets.LyricsSidecar(path), []byte(s.lyrics+"\n"), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		os.Chtimes(path, s.when, s.when)
	}
}

// seedSessions writes the named stations that head the station list.
func seedSessions(t *testing.T, sb *sandbox) {
	t.Helper()
	store := session.NewStore(filepath.Join(sb.dir, "data", "sessions"))
	for i, d := range demoSessions {
		played := time.Date(2026, 3, 15, 8, 0, 0, 0, time.UTC).Add(-time.Duration(i) * 26 * time.Hour)
		s := session.New()
		s.Name = d.name
		s.BasePrompt = d.prompt
		s.Named = true
		s.Vocal = true
		// A station sings in the languages it was saved with; the demo
		// ones say English, which is what the pills should show.
		s.SungLanguages = []string{"English"}
		s.Created = played.Add(-72 * time.Hour)
		s.Updated = played
		s.LastPlayed = played
		if err := store.Save(s); err != nil {
			t.Fatal(err)
		}
	}
}

// tone renders a quiet sine of the given length, the stand-in for a
// generated song in the invented library.
func tone(seconds int, freq float64) []int16 {
	samples := make([]int16, seconds*audio.SampleRate*audio.Channels)
	for i := 0; i < len(samples); i += 2 {
		v := int16(6000 * math.Sin(2*math.Pi*freq*float64(i/2)/audio.SampleRate))
		samples[i], samples[i+1] = v, v
	}
	return samples
}
